### ISSUE TITLE
A script is required to handle the filtering of data and sending it to sheets

### ISSUE THREAD

**Issue by thekodeking** [Open-Source-Community-VIT-AP/oschub#30]
# Tasks that might solve the issue

- [x] Fixing the code by adding model filtering methods and getting data in the required format of lists
- [x] Verifying the obtained list by event name
- [x] Verify whether the event is over or not
- [x] Finally, send the data to GSheets using Batch Update

**Closing this issue will finish most of the backend-database stuff**
